services:

  cloudworkloads:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CloudWorkload
    restart: no
    ports:
      - 8081:8080
    depends_on:
      - assessment


  assessment:
    image: mrksdh/assessment
    container_name: assessment
    restart: unless-stopped
    ports:
      - 8080:8080