name: CloudWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      # Repository auschecken
      - name: Check out repository
        uses: actions/checkout@v3

      # Setze Java ein (z. B. Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build des Maven-Projekts
      - name: Build with Maven
        run: mvn clean install

      # Docker Compose installieren
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      # Docker Compose starten
      - name: Start Docker Compose
        run: docker-compose up

      # Optional: Tests oder andere Schritte ausführen
      - name: Run Tests
        run: mvn test

